server:
  port: 9091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**, /api/v1/admin/products/**

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/**, /api/v1/admin/orders/**

        - id: payment-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

security:
  internal-api-key: ${INTERNAL_API_KEY}

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: true
