server:
  port: 8083

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.commondto.kafka"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    loadbalancer:
      retry:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: ${USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
  timelimiter:
    instances:
      payment-service:
        timeout-duration: 3s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

security:
  internal-api-key: ${INTERNAL_API_KEY}