server:
  port: 8083

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.commondto.kafka"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    loadbalancer:
      retry:
        enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://order-postgres:5432/order_service_db}
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:redis}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        register-health-indicator: true
    instances:
      product-service: {}
      user-service: {}
      payment-service:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 20s
        minimum-number-of-calls: 5

  timelimiter:
    configs:
      default:
        timeout-duration: 2s
        cancel-running-future: true
    instances:
      product-service: {}
      user-service: {}
      payment-service:
        timeout-duration: 3s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
      registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

security:
  internal-api-key: ${SECURITY_INTERNAL_API_KEY}