server:
  port: 8111
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/items/**

