server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: ${USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin