server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: ${USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
jwt:
  secret: ${JWT_SECRET}}
  expiration: 3_600_000 # 1 hour
  refresh-token: 86_400_000 # 24 hours